[package]
name = "rdiff"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
comfy-table = "7.1.1"
crossterm = "0.28.1"
ratatui = { version = "0.27.0", features = ["all-widgets"] }
